micronaut:
  application:
    name: shoppingCardApi

grpc:
  channels:
    discount:
      address: ${DISCOUNT_SERVICE_ENDPOINT}
      plaintext: true
      max-retry-attempts: 10

dateBlackFriday: ${DATE_BLACK_FRIDAY}