micronaut:
  application:
    name: shoppingCardApi

grpc:
  channels:
    discount:
      address: "http://localhost:50051" ##TODO: Add en environment variable
      plaintext: true
      max-retry-attempts: 10


dateBlackFriday: "2022-11-25"